# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

# [sncast.default]                                         # Define a profile name
# url = "https://free-rpc.nethermind.io/sepolia-juno/v0_7" # Url of the RPC provider
# accounts-file = "../account-file"                        # Path to the file with the account data
# account = "mainuser"                                     # Account from `accounts_file` or default account file that will be used for the transactions
# keystore = "~/keystore"                                  # Path to the keystore file
# wait-params = { timeout = 300, retry-interval = 10 }     # Wait for submitted transaction parameters
# block-explorer = "StarkScan"                            # Block explorer service used to display links to transaction details
# show-explorer-links = true                              # Print links pointing to pages with transaction details in the chosen block explorer

[sncast.testacc]
account = "testacc"
accounts-file = "/Users/onchez/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050"

# [sncast.test]
# account = "test"
# accounts-file = "/Users/onchez/.starknet_accounts/starknet_open_zeppelin_accounts.json"
# url = "http://127.0.0.1:5050"

[sncast.user]
account = "user"
accounts-file = "/Users/onchez/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050"

[sncast.argent]
account = "argent"
accounts-file = "/Users/onchez/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"

[sncast.starhomes_devnet]
account = "starhomes_devnet"
accounts-file = "/Users/onchez/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050"

[sncast.starhomes_dev_argrent]
account = "starhomes_dev_argrent"
accounts-file = "/Users/onchez/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://127.0.0.1:5050"
[sncast.braavos]
account = "braavos_account"
accounts-file = "../account-file"
url = ""

[sncast.braavos1]
account = "braavos"
accounts-file = "../account-file"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
